"""latest revisions

Revision ID: 428c6a522dc9
Revises: 
Create Date: 2022-10-14 02:26:23.448073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '428c6a522dc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todolist_id'), 'todolist', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todolist_id'), table_name='todolist')
    op.drop_table('todolist')
    # ### end Alembic commands ###
