"""latest revisions

Revision ID: 5b3fe7d9fc89
Revises: 
Create Date: 2022-10-13 04:41:51.568294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3fe7d9fc89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('optionA', sa.String(), nullable=True),
    sa.Column('optionB', sa.String(), nullable=True),
    sa.Column('optionC', sa.String(), nullable=True),
    sa.Column('optionD', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_index(op.f('ix_questions_question_id'), 'questions', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_question_id'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
