"""latest revisions

Revision ID: e7ba8bc0a8a9
Revises: 5b3fe7d9fc89
Create Date: 2022-10-13 09:39:59.430691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7ba8bc0a8a9'
down_revision = '5b3fe7d9fc89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todolist_id'), 'todolist', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todolist_id'), table_name='todolist')
    op.drop_table('todolist')
    # ### end Alembic commands ###
